//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.19 at 03:02:05 PM CEST 
//


package jmediainspector.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jmediainspector.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jmediainspector.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Application.Searchs }
     * 
     */
    public Application.Searchs createApplicationSearchs() {
        return new Application.Searchs();
    }

    /**
     * Create an instance of {@link Application.Searchs.Search }
     * 
     */
    public Application.Searchs.Search createApplicationSearchsSearch() {
        return new Application.Searchs.Search();
    }

    /**
     * Create an instance of {@link Application.Searchs.Search.Criterias }
     * 
     */
    public Application.Searchs.Search.Criterias createApplicationSearchsSearchCriterias() {
        return new Application.Searchs.Search.Criterias();
    }

    /**
     * Create an instance of {@link Application.Searchs.Search.Criterias.Criteria }
     * 
     */
    public Application.Searchs.Search.Criterias.Criteria createApplicationSearchsSearchCriteriasCriteria() {
        return new Application.Searchs.Search.Criterias.Criteria();
    }

    /**
     * Create an instance of {@link Application.Searchs.Search.Criterias.Criteria.Filters }
     * 
     */
    public Application.Searchs.Search.Criterias.Criteria.Filters createApplicationSearchsSearchCriteriasCriteriaFilters() {
        return new Application.Searchs.Search.Criterias.Criteria.Filters();
    }

    /**
     * Create an instance of {@link Application.Plex }
     * 
     */
    public Application.Plex createApplicationPlex() {
        return new Application.Plex();
    }

    /**
     * Create an instance of {@link Application.Plex.Configuration }
     * 
     */
    public Application.Plex.Configuration createApplicationPlexConfiguration() {
        return new Application.Plex.Configuration();
    }

    /**
     * Create an instance of {@link Application.Searchs.Search.Criterias.Criteria.Filters.Filter }
     * 
     */
    public Application.Searchs.Search.Criterias.Criteria.Filters.Filter createApplicationSearchsSearchCriteriasCriteriaFiltersFilter() {
        return new Application.Searchs.Search.Criterias.Criteria.Filters.Filter();
    }

    /**
     * Create an instance of {@link Application.Plex.Configuration.Paths }
     * 
     */
    public Application.Plex.Configuration.Paths createApplicationPlexConfigurationPaths() {
        return new Application.Plex.Configuration.Paths();
    }

}
